name: Run Cloud PC (Ubuntu)

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start cloud terminal
        run: |
          echo "Your cloud PC is ready!"
          sleep 3600  # 1 ghanta tak run karega
